name: $(Date:yyyyMMdd)
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/node-grpc/*
pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/node-grpc/*
pool:
  vmImage: ubuntu-16.04

variables:
- group: env-prod
- group: bintray-credentials-ds

steps:
- template: templates/build_opkg.yaml
  timeoutInMinutes: 180
  parameters:
    pkgName: node-grpc
    imageName: 'saw1/build-turris-ipkg-node:latest'

- template: templates/publish-opkg-bintray.yaml
  parameters:
    pkgName: node-grpc
