name: $(Date:yyyyMMdd)
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/node-grpc/*
pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/node-grpc/*
pool:
  vmImage: ubuntu-16.04
  timeoutInMinutes: 180


variables:
- group: env-dev
- group: bintray-credentials-ds

steps:
- template: templates/build-opkg.yaml
  parameters:
    srcDir:  $(Build.SourcesDirectory)/router/openwrt_pkgs
    outDir: $(Build.StagingDirectory)
    pkgName: node-grpc
    imageName: 'saw1/build-turris-ipkg-node:latest'

- template: templates/publish-opkg-bintray.yaml
  parameters:
    pkgName: node-grpc
