name: $(Date:yyyyMMdd)
trigger: none
pr: none
pool:
  vmImage: ubuntu-16.04

variables:
- group: env-prod
- group: bintray-credentials-ds

steps:
- bash: 'chmod 777 $(Build.StagingDirectory)'
  displayName: 'Set Permissions on temporary staging directory'

- task: Docker@1
  displayName: 'Extract Node ipk Packages from Docker Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Daniel-DockerHub'
    command: run
    runInBackground: false
    imageName: 'saw1/build-turris-ipkg-node:latest'
    volumes:  |
      $(Build.StagingDirectory):/dist
    containerCommand: 'cp -r ./bin/packages/arm_cortex-a9_vfpv3/node/. /dist/'

- bash: echo "##vso[task.setvariable variable=version]$(ls node_* | awk -F'[_]' '{print substr($2,1,length($2)-2)}')"
  workingDirectory: $(Build.StagingDirectory)
  displayName: 'Parse Version Number from ipk Packages'

- task: Docker@1
  displayName: 'Publish ipk Files to Bintray opkg Repository'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Daniel-DockerHub'
    command: run
    runInBackground: false
    imageName: 'saw1/deploy-bintray:latest'
    volumes:  |
      $(Build.StagingDirectory):/deploy
    envVars: |
      BINTRAY_CREDENTIALS=$(BINTRAY_CREDENTIALS)
      BINTRAY_REPO=$(BINTRAY_REPO_OPENWRT)
      PKG_NAME=node
      PKG_VERSION=$(version)
