name: $(Date:yyyyMMdd)
trigger: none
pr: none

pool:
  vmImage: ubuntu-16.04
steps:
- bash: 'chmod 777 $(Build.StagingDirectory)'
  displayName: 'Set Permissions on temporary staging directory'

- task: Docker@1
  displayName: 'Extract Node ipk Packages from Docker Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Daniel-DockerHub'
    command: run
    runInBackground: false
    imageName: 'saw1/build-turris-ipkg-node:latest'
    volumes:  |
      $(Build.StagingDirectory):/dist
    containerCommand: 'cp -r ./bin/packages/arm_cortex-a9_vfpv3/node/. /dist/'

- bash: echo "##vso[task.setvariable variable=version]$(ls node_* | awk -F'[_]' '{print substr($2,1,length($2)-2)}')"
  workingDirectory: $(Build.StagingDirectory)
  displayName: 'Parse Version Number from ipk Packages'

- task: PublishPipelineArtifact@0
  displayName: 'Publish ipk Files to STAGING'
  inputs:
    artifactName: node-$(version)
    targetPath: $(Build.StagingDirectory)
