name: $(Date:yyyyMMdd)
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/saw/*
    - router/*
    exclude:
    - router/openwrt_pkgs/*
pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    include:
    - router/openwrt_pkgs/saw/*
    - router/*
    exclude:
    - router/openwrt_pkgs/*

variables:
- group: env-prod
- group: bintray-credentials-ds

jobs:
- job: solc
  displayName: 'Compile Smart Contract'
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: templates/build-solc.yaml
    parameters:
      contractsDir: $(Build.SourcesDirectory)/smart_contracts
      contractFile: saw_contract.sol

- job: protoc
  displayName: 'Compile Protobuf (gRPC) definitions'
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: templates/build-protoc.yaml
    parameters:
      protobufDir: $(Build.SourcesDirectory)/protobuf
      outDir: $(Build.SourcesDirectory)/router/src/grpc

- job: saw-ts
  displayName: 'Compile SAW TypeScript'
  dependsOn: protoc
  condition: succeeded()
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadPipelineArtifact@1
    inputs:
      artifactName: saw-service-protobuf
      downloadPath: $(Build.SourcesDirectory)/router/src/grpc
  - template: templates/build-ts.yaml
    parameters:
      srcDir: $(Build.SourcesDirectory)/router
      outDir: $(Build.SourcesDirectory)/router/build

- job: saw-openwrt
  displayName: 'Package SAW for OpenWrt (opkg)'
  dependsOn:
  - solc
  - saw-ts
  condition: succeeded()
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadPipelineArtifact@1
    inputs:
      buildType: current
      artifactName: saw-contract
      downloadPath: $(Build.SourcesDirectory)/router/openwrt_pkgs/saw/files/etc/saw
  
  - task: DownloadPipelineArtifact@1
    inputs:
      buildType: current
      artifactName: saw-service-ts
      downloadPath: $(Build.SourcesDirectory)/router/openwrt_pkgs/saw/files/etc/saw'

  - bash: 'find ./openwrt_pkgs -mindepth 1 ! -regex "^./openwrt_pkgs/saw\(/.*\)?" -delete'
    displayName: 'Extract SAW openwrt source package from feed (skip building dependencies)'
    workingDirectory: $(Build.SourcesDirectory)/router
  - template: templates/tools-docker-turris-ipkg.yaml
    parameters:
      srcDir:  $(Build.SourcesDirectory)/router/openwrt_pkgs
      outDir: $(Build.StagingDirectory)
      pkgName: saw
  
  - task: PublishPipelineArtifact@0
    displayName: 'Publish artifact for release pipeline'
    inputs:
      artifactName: saw-service-opkg
      targetPath: $(Build.StagingDirectory)
