name: $(Date:yyyyMMdd)
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - tools/dockerfiles/build-protobuf/dockerfile
pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    include:
    - tools/dockerfiles/build-protobuf/dockerfile

pool:
      vmImage: ubuntu-16.04

steps:
- template: templates/docker-build.yaml
  parameters:
    imagename: build-protobuf
