ARG TOOLCHAIN_VERSION=latest-omnia-hbk-openwrt-18.06
FROM saw1/build-turris-ipkg:${TOOLCHAIN_VERSION}

ENV SAW_BRANCH=master

WORKDIR /home/beast
RUN git clone --depth 1 https://github.com/DanielSel/saw.git -b ${SAW_BRANCH} \
 && find ./saw -mindepth 1 ! -regex '^./saw/router\(/openwrt_pkgs\(/node\(/.*\)?\)?\)?' -delete

WORKDIR /home/beast/${SDK_NAME}
RUN echo "src-link node /home/beast/saw/router/openwrt_pkgs" >> feeds.conf.default
RUN ./scripts/feeds update node \
 && ./scripts/feeds install -p node node

RUN make defconfig \
    && make -j $((`nproc`+1)) package/node/compile V=sc \
    && make -j $((`nproc`+1)) package/node/host/compile V=sc 
