FROM alpine:3.9
RUN apk add --update curl && rm -rf /var/cache/apk/*

# ENV BINTRAY_CREDENTIALS
# ENV BINTRAY_REPO

# ENV PKG_NAME
# ENV PKG_VERSION

WORKDIR /deploy
CMD for FILE in *; do curl -T $FILE -u${BINTRAY_CREDENTIALS} https://api.bintray.com/content/${BINTRAY_REPO}/${PKG_NAME}/${PKG_VERSION}/$FILE?override=1; done \
    && curl -X POST -u${BINTRAY_CREDENTIALS} https://api.bintray.com/content/${BINTRAY_REPO}/${PKG_NAME}/${PKG_VERSION}/publish

VOLUME /deploy