#!/bin/sh /etc/rc.common

START=87
USE_PROCD=1

start_service() {

    # Load Configuration
    config_load saw

    config_get contract_wallet_mnemonic user contract_wallet_mnemonic
    config_get contract_wallet_privatekey user contract_wallet_privatekey
    config_get contract_network user contract_network

    config_get debug main debug
    config_get log_level main log_level
    config_get allow_offline_operation main allow_offline_operation
    config_get shutdown_kill_timeout main shutdown_kill_timeout
    config_get contract_json_path main contract_json_path
    config_get contract_address main contract_address
    config_get contract_infura_token main contract_infura_token
    config_get cashout_threshold main cashout_threshold
    config_get cashout_interval main cashout_interval
    config_get session_inactivity_threshold main session_inactivity_threshold
    config_get blacklist_time main blacklist_time

    config_get max_pop_interval policy max_pop_interval
    config_get pop_tolerance policy pop_tolerance
    config_get min_initial_funds policy min_initial_funds


    procd_open_instance saw
    procd_set_param command /usr/bin/node /etc/saw/SawService.js

    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/config/saw
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root

    

    # Required Config
    procd_set_param env \
    SAW_CONTRACT_WALLET_MNEMONIC="$contract_wallet_mnemonic" \
    SAW_CONTRACT_WALLET_PRIVATEKEY=$contract_wallet_privatekey \
    SAW_CONTRACT_NETWORK=$contract_network \
    SAW_DEBUG=$debug \
    SAW_LOG_LEVEL=$log_level \
    SAW_ALLOW_OFFLINE_OPERATION=$allow_offline_operation \
    SAW_SHUTDOWN_KILL_TIMEOUT=$shutdown_kill_timeout \
    SAW_CONTRACT_JSON_PATH="$contract_json_path" \
    SAW_CONTRACT_ADDRESS=$contract_address \
    SAW_CONTRACT_INFURA_TOKEN=$contract_infura_token \
    SAW_CASHOUT_THRESHOLD=$cashout_threshold \
    SAW_CASHOUT_INTERVAL=$cashout_interval \
    SAW_SESSION_INACTIVITY_THRESHOLD=$session_inactivity_threshold \
    SAW_BLACKLIST_TIME=$blacklist_time \
    SAW_MAX_POP_INTERVAL=$max_pop_interval \
    SAW_POP_TOLERANCE=$pop_tolerance \
    SAW_MIN_INITIAL_FUNDS=$min_initial_funds

    procd_close_instance
}
