#!/bin/sh /etc/rc.common

START=87
USE_PROCD=1

start_service() {

    # Load Configuration
    config_load saw

    config_get contract_infura_token user contract_infura_token
    config_get contract_wallet_mnemonic user contract_wallet_mnemonic
    config_get contract_network user contract_network

    config_get debug main debug
    config_get log_level main log_level
    config_get allow_offline_operation main allow_offline_operation
    config_get shutdown_kill_timeout main shutdown_kill_timeout
    config_get contract_json_path main contract_json_path
    config_get contract_address main contract_address
    config_get cashout_threshold main cashout_threshold
    config_get cashout_interval main cashout_interval
    config_get session_inactivity_threshold main session_inactivity_threshold
    config_get blacklist_time main blacklist_time

    config_get max_pop_interval policy max_pop_interval
    config_get pop_tolerance policy pop_tolerance
    config_get min_initial_funds policy min_initial_funds


    procd_open_instance saw
    procd_set_param command /usr/bin/node /etc/saw/SawService.js

    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/config/saw
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody

    

    # Required Config
    procd_set_param env SAW_CONTRACT_INFURA_TOKEN=$contract_infura_token
    procd_set_param env SAW_CONTRACT_WALLET_MNEMONIC=$contract_wallet_mnemonic
    procd_set_param env SAW_CONTRACT_NETWORK=$contract_network
    

    # Customization
    procd_set_param env SAW_DEBUG=$debug
    procd_set_param env SAW_LOG_LEVEL=$log_level
    procd_set_param env SAW_ALLOW_OFFLINE_OPERATION=$allow_offline_operation
    procd_set_param env SAW_SHUTDOWN_KILL_TIMEOUT=$shutdown_kill_timeout

    procd_set_param env SAW_CONTRACT_JSON_PATH=$contract_json_path
    procd_set_param env SAW_CONTRACT_ADDRESS=$contract_address

    procd_set_param env SAW_CASHOUT_THRESHOLD=$cashout_threshold
    procd_set_param env SAW_CASHOUT_INTERVAL=$cashout_interval
    procd_set_param env SAW_SESSION_INACTIVITY_THRESHOLD=$session_inactivity_threshold
    procd_set_param env SAW_BLACKLIST_TIME=$blacklist_time

    # Admission Policy
    procd_set_param env SAW_MAX_POP_INTERVAL=$max_pop_interval
    procd_set_param env SAW_POP_TOLERANCE=$pop_tolerance
    procd_set_param env SAW_MIN_INITIAL_FUNDS=$min_initial_funds

    procd_close_instance
}
